name: Handle orders

on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r src/stripe_handler/requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL_USERNAME }}
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: python src/stripe_handler/OrdersHandler.py

      - name: Update GitHub with latest processed payments
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update processed payments"
          file_pattern: 'src/stripe_handler/data/processed_payments.csv'
